name: react-action
on: workflow_dispatch
jobs:
  test-application:
    runs-on: ubuntu-latest
    steps:
      - name: download repository
        uses: actions/checkout@v4
      - name: install needed dependencies
        working-directory: "02 Starting Project/"
        run: npm ci
      - name: running tests
        working-directory: "02 Starting Project/"
        run: npm test
