name: react-action
on: workflow_dispatch
jobs:
  run-application:
    runs-on: ubuntu-latest
    steps:
      - name: go to react folder
        run: |
          echo "Abl m n5ush l folder"
          cd '02 Starting Project/'
          echo "d5lna l folder"
      - name: Install dependencies
        run: |
          echo "Abl m n install l dependencies"
          npm install
          echo "b3d m n install l dependencies"
      - name: run tests
        run: npm test
      - name: run the server
        run: npm run dev
