name: react-action
on: workflow_dispatch
jobs:
  run-application:
    runs-on: ubuntu-latest
    steps:
      - name: download repository
        uses: actions/checkout@v4
      - name: go to react project folder
        run: |
          ls
          cd '02 Starting Project/'
          echo "ana dkhlt gwa"
          ls
      - name: install needed dependencies
        run:  |
        ls    
        npm install
      - name: run the application
        run: npm run dev
