name: react-action
on: workflow_dispatch
jobs:
  run-application:
    runs-on: ubuntu-latest
    steps:
      - name: download repository
        uses: actions/checkout@v4
      - name: install needed dependencies
        run: |
          cd '02 Starting Project/'   
          npm ci
          npm test
